server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server




  cloud:
    config:
      server:
        git:
          uri: file:\\\C:\Users\User\Documents\Workspace\CodeCake\UdemyMicroservice
      profile: dev