spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 1072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


resilience4j:
  retry:
    instances:
      test-circuit-braker:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      defaultLimiter:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      defaultLimiter:
        max-concurrent-calls: 10

management:
  tracing:
    sampling:
      probability: 1.0

#logging:
 # pattern:
 #   level: %5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

