spring:
  application:
    name: currency-conversion-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 1073
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

